# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/School/Vivado/ZynqHelloFreeRTOS/ZynqHelloFreeRTOS.srcs/sources_1/bd/main/ip/main_processing_system7_0_0/main_processing_system7_0_0.xci
# IP: The module: 'main_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/School/Vivado/ZynqHelloFreeRTOS/ZynqHelloFreeRTOS.gen/sources_1/bd/main/ip/main_processing_system7_0_0/main_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/School/Vivado/ZynqHelloFreeRTOS/ZynqHelloFreeRTOS.srcs/sources_1/bd/main/ip/main_processing_system7_0_0/main_processing_system7_0_0.xci
# IP: The module: 'main_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/School/Vivado/ZynqHelloFreeRTOS/ZynqHelloFreeRTOS.gen/sources_1/bd/main/ip/main_processing_system7_0_0/main_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
